import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const inter = localFont({
  src:"./fonts/Inter-Regular.otf",
})
export const interBold = localFont({
  src:"./fonts/Inter-Bold.otf",
  variable:"--Inter-Bold",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
